development:
  adapter: postgresql
  database: core_values_development
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  database: core_values_production
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  database: core_values_test
  pool: 5
  username:
  password:
